### PR TITLE
[CNNLCORE-9872]test(three_interpolate_backward): add three_interpolat…

### PR DESCRIPTION
**Pull request by FRYao**
…e_backward api gtest

Thanks for your contribution and we appreciate it a lot. 

## 1. Motivation

Please describe your motivation and the goal you want to achieve through this pull request.

## 2. Modification

Please briefly describe what modification is made in this pull request, and indicate where to make the modification.

## 3. Test Report

If you want to know how to do operator testing, you can see [GTest-User-Guide-zh](../docs/GTest-User-Guide-zh.md).

#### 3.1.1 Accuracy Acceptance Standard

For static threshold standard details, see: [MLU-OPS Accuracy Acceptance Standard](../docs/MLU-OPS-Accuracy-Acceptance-Standard.md).

- [ ] diff1, diff1 <= 3e-3
- [ ] diff2, diff2 <= 3e-3

#### 3.1.2 Operator Scheme checklist

|     No.      |           Details            |      Check Results       |
|----------------|---------------------------|---------------------|
|        1       |          Supported hardware         | MLU370<br>MLU590|
|        2       |          Job types          |    block <br> U1 <br> U4    |
|        3       |         Layouts            |  NHWC 、NCHW、ARRAY etc    |
|        4       |         Whether multi-dimensions are supported              |                |
|        5       |          Whether element zero is supported             |               |
|        6       |         Data type(half/float)       |         half / float etc           |
|        7      |        Whether there is size limit           |             |

#### 3.1.3 New Feature Test

If you have checked the following items, please tick the relevant box.

- [ ] Data type test
- [ ] Multidimensional tensor test
- [ ] Layout test
- [ ] Different size/integer remainder end segment/alignment misalignment test
- [ ] Zero dimensional tensor test/zero element test
- [ ] stability test
- [ ] Multiple platform test
- [ ] Gen_case module test
- [ ] Nan/INF tests 
- [ ] Bug fix tests
- [ ] For memory leak check details, see[GTest-User-Guide-zh](../docs/GTest-User-Guide-zh.md).
- [ ] For code coverage check details, see: [GTest-User-Guide-zh](../docs/GTest-User-Guide-zh.md).
- [ ] For I/O calculation efficiency check details, see: [MLU-OPS Performance Acceptance Standard](../docs/MLU-OPS-Performance-Acceptance-Standard.md).

#### 3.1.4 Parameter Check

When a new operator is submitted, the test points are given and the test results are stated.

| Test Point         | Acceptance Standard | Test Result (Error Message) |
| -------------- | -------- | -------------------- |
| Whether it conforms to the operator restriction | Normal error |                      |
| Whether illegal parameters are passed  | Normal error |                      |

### 3.2 Accuracy Test

For the cases used in the New Feature Test section, the features and the number of cases are recorded here. When multiple operations are tested, multiple tables are needed to include details of these operations.

Operation:

|Test Point           | Description      | Quantity |  Comment |
|----------           |----------        |----------|   ----------    |
|Data type test       |half/float/int8|          |                 |
|Mult-tensor test     |Supports 1-8 dims|          |                 |
|Layout test          |Supports NCHW/NHWC|          |                 |
|Zero element test    |Whether to support this test |          |                 |
|Stability test       |--gtest_repeat=NUM<br>--thread=NUM |          |                 |
|Mult-platform test   |MLU370/MLU590  |          |                 |
|Nan/INF test        |Whether to support this test   |          |                 |

### 3.3 Performance Test

See [MLU-OPS Performance Acceptance Standard](../docs/MLU-OPS-Performance-Acceptance-Standard.md) for details.

Platform：MLU370

|Operation|Mlu_hardware_time(us)|Mlu_interface_time(us)|Mlu_io_efficiency|Mlu_compute_efficiency|Mlu_workwpace_size(Bytes)|Data_type|Shape|
|-----|----|----|----|----|----|------|-----|
|op_name|   |    |     |    |    |    |     |
|op_name|   |    |     |    |    |    |     |

Platform：MLU590

|Operation|Mlu_hardware_time(us)|Mlu_interface_time(us)|Mlu_io_efficiency|Mlu_compute_efficiency|Mlu_workwpace_size(Bytes)|Data_type|Shape|
|-----|----|----|----|----|----|------|-----|
|op_name|   |    |     |    |    |    |     |
|op_name|   |    |     |    |    |    |     |

### 3.4 Summary Analysis

Please give a brief overview here, if you want to note and summarize the content.

### CODE REVIEW

**Review by Shin-Wang — APPROVED** [review]
LGTM

**Comment by ArtIntAI** [comment]
LGTM

**Review by LittleReal — APPROVED** [review]
LGTM

**Comment by FRYao** [comment]
测试报告：
```
[----------] 1 test from zero_element_B_0/three_interprolate_backward_general
[ RUN      ] zero_element_B_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Zero element tensor failure.
[       OK ] zero_element_B_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from zero_element_B_0/three_interprolate_backward_general (0 ms total)

[----------] 1 test from zero_element_C_1/three_interprolate_backward_general
[ RUN      ] zero_element_C_1/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Zero element tensor failure.
[       OK ] zero_element_C_1/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from zero_element_C_1/three_interprolate_backward_general (0 ms total)

[----------] 1 test from zero_element_C_0/three_interprolate_backward_general
[ RUN      ] zero_element_C_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Zero element tensor failure.
[       OK ] zero_element_C_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from zero_element_C_0/three_interprolate_backward_general (0 ms total)

[----------] 1 test from zero_element_N_0/three_interprolate_backward_general
[ RUN      ] zero_element_N_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Zero element tensor failure.
[       OK ] zero_element_N_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from zero_element_N_0/three_interprolate_backward_general (0 ms total)

[----------] 1 test from zero_element_M_0/three_interprolate_backward_general
[ RUN      ] zero_element_M_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dims[2] should be equal to indices_desc->dims[1].
[       OK ] zero_element_M_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from zero_element_M_0/three_interprolate_backward_general (0 ms total)

[----------] 1 test from bad_dtype_0/three_interprolate_backward_general
[ RUN      ] bad_dtype_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: (grad_output_desc->dtype == MLUOP_DTYPE_HALF || grad_output_desc->dtype == MLUOP_DTYPE_FLOAT). 
[       OK ] bad_dtype_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from bad_dtype_0/three_interprolate_backward_general (0 ms total)

[----------] 1 test from bad_indices_weight_shape_0/three_interprolate_backward_general
[ RUN      ] bad_indices_weight_shape_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: weights_desc->dims[2] should be equal to 3.
[       OK ] bad_indices_weight_shape_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from bad_indices_weight_shape_0/three_interprolate_backward_general (0 ms total)

[----------] 4 tests from bad_grad_features_shape_dtype_0/three_interprolate_backward_general
[ RUN      ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dims[0] should be equal to grad_features_desc->dims[0].
[       OK ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/0 (0 ms)
[ RUN      ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/1
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_features_desc->dim == 3. 
[       OK ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/1 (0 ms)
[ RUN      ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/2
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_features_desc->dim == 3. 
[       OK ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/2 (0 ms)
[ RUN      ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/3
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: weights_desc->dtype == grad_features_desc->dtype. 
[       OK ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/3 (1 ms)
[----------] 4 tests from bad_grad_features_shape_dtype_0/three_interprolate_backward_general (1 ms total)

[----------] 6 tests from bad_weight_shape_dtype_0/three_interprolate_backward_general
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dims[0] should be equal to weightss_desc->dims[0].
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/0 (0 ms)
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/1
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dims[1] should be equal to weightss_desc->dims[1].
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/1 (0 ms)
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/2
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dims[2] should be equal to weightss_desc->dims[2].
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/2 (0 ms)
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/3
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: weights_desc->dim == 3. 
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/3 (0 ms)
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/4
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: weights_desc->dim == 3. 
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/4 (0 ms)
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/5
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dtype == weights_desc->dtype. 
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/5 (0 ms)
[----------] 6 tests from bad_weight_shape_dtype_0/three_interprolate_backward_general (0 ms total)

[----------] 6 tests from bad_indices_shape_dtype_0/three_interprolate_backward_general
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dims[0] should be equal to indices_desc->dims[0].
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/0 (0 ms)
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/1
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dims[1] should be equal to weightss_desc->dims[1].
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/1 (0 ms)
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/2
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dims[2] should be equal to weightss_desc->dims[2].
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/2 (0 ms)
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/3
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dim == 3. 
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/3 (0 ms)
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/4
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dim == 3. 
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/4 (0 ms)
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/5
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dtype == MLUOP_DTYPE_INT32. 
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/5 (0 ms)
[----------] 6 tests from bad_indices_shape_dtype_0/three_interprolate_backward_general (0 ms total)

[----------] 5 tests from bad_grad_output_shape_dtype_0/three_interprolate_backward_general
[ RUN      ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dims[0] should be equal to indices_desc->dims[0].
[       OK ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/0 (0 ms)
[ RUN      ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/1
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dims[1] should be equal to grad_features_desc->dims[1].
[       OK ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/1 (0 ms)
[ RUN      ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/2
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dim == 3. 
[       OK ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/2 (0 ms)
[ RUN      ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/3
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dim == 3. 
[       OK ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/3 (0 ms)
[ RUN      ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/4
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dtype == weights_desc->dtype. 
[       OK ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/4 (0 ms)
[----------] 5 tests from bad_grad_output_shape_dtype_0/three_interprolate_backward_general (0 ms total)

```

**Comment by FRYao** [comment]
测试报告：
```
[----------] 1 test from zero_element_B_0/three_interprolate_backward_general
[ RUN      ] zero_element_B_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Zero element tensor failure.
[       OK ] zero_element_B_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from zero_element_B_0/three_interprolate_backward_general (0 ms total)

[----------] 1 test from zero_element_C_1/three_interprolate_backward_general
[ RUN      ] zero_element_C_1/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Zero element tensor failure.
[       OK ] zero_element_C_1/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from zero_element_C_1/three_interprolate_backward_general (0 ms total)

[----------] 1 test from zero_element_C_0/three_interprolate_backward_general
[ RUN      ] zero_element_C_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Zero element tensor failure.
[       OK ] zero_element_C_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from zero_element_C_0/three_interprolate_backward_general (0 ms total)

[----------] 1 test from zero_element_N_0/three_interprolate_backward_general
[ RUN      ] zero_element_N_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Zero element tensor failure.
[       OK ] zero_element_N_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from zero_element_N_0/three_interprolate_backward_general (0 ms total)

[----------] 1 test from zero_element_M_0/three_interprolate_backward_general
[ RUN      ] zero_element_M_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dims[2] should be equal to indices_desc->dims[1].
[       OK ] zero_element_M_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from zero_element_M_0/three_interprolate_backward_general (0 ms total)

[----------] 1 test from bad_dtype_0/three_interprolate_backward_general
[ RUN      ] bad_dtype_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: (grad_output_desc->dtype == MLUOP_DTYPE_HALF || grad_output_desc->dtype == MLUOP_DTYPE_FLOAT). 
[       OK ] bad_dtype_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from bad_dtype_0/three_interprolate_backward_general (0 ms total)

[----------] 1 test from bad_indices_weight_shape_0/three_interprolate_backward_general
[ RUN      ] bad_indices_weight_shape_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: weights_desc->dims[2] should be equal to 3.
[       OK ] bad_indices_weight_shape_0/three_interprolate_backward_general.api_test/0 (0 ms)
[----------] 1 test from bad_indices_weight_shape_0/three_interprolate_backward_general (0 ms total)

[----------] 4 tests from bad_grad_features_shape_dtype_0/three_interprolate_backward_general
[ RUN      ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dims[0] should be equal to grad_features_desc->dims[0].
[       OK ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/0 (0 ms)
[ RUN      ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/1
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_features_desc->dim == 3. 
[       OK ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/1 (0 ms)
[ RUN      ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/2
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_features_desc->dim == 3. 
[       OK ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/2 (0 ms)
[ RUN      ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/3
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: weights_desc->dtype == grad_features_desc->dtype. 
[       OK ] bad_grad_features_shape_dtype_0/three_interprolate_backward_general.api_test/3 (1 ms)
[----------] 4 tests from bad_grad_features_shape_dtype_0/three_interprolate_backward_general (1 ms total)

[----------] 6 tests from bad_weight_shape_dtype_0/three_interprolate_backward_general
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dims[0] should be equal to weightss_desc->dims[0].
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/0 (0 ms)
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/1
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dims[1] should be equal to weightss_desc->dims[1].
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/1 (0 ms)
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/2
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dims[2] should be equal to weightss_desc->dims[2].
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/2 (0 ms)
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/3
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: weights_desc->dim == 3. 
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/3 (0 ms)
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/4
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: weights_desc->dim == 3. 
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/4 (0 ms)
[ RUN      ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/5
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dtype == weights_desc->dtype. 
[       OK ] bad_weight_shape_dtype_0/three_interprolate_backward_general.api_test/5 (0 ms)
[----------] 6 tests from bad_weight_shape_dtype_0/three_interprolate_backward_general (0 ms total)

[----------] 6 tests from bad_indices_shape_dtype_0/three_interprolate_backward_general
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dims[0] should be equal to indices_desc->dims[0].
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/0 (0 ms)
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/1
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dims[1] should be equal to weightss_desc->dims[1].
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/1 (0 ms)
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/2
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dims[2] should be equal to weightss_desc->dims[2].
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/2 (0 ms)
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/3
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dim == 3. 
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/3 (0 ms)
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/4
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dim == 3. 
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/4 (0 ms)
[ RUN      ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/5
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: indices_desc->dtype == MLUOP_DTYPE_INT32. 
[       OK ] bad_indices_shape_dtype_0/three_interprolate_backward_general.api_test/5 (0 ms)
[----------] 6 tests from bad_indices_shape_dtype_0/three_interprolate_backward_general (0 ms total)

[----------] 5 tests from bad_grad_output_shape_dtype_0/three_interprolate_backward_general
[ RUN      ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/0
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dims[0] should be equal to indices_desc->dims[0].
[       OK ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/0 (0 ms)
[ RUN      ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/1
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dims[1] should be equal to grad_features_desc->dims[1].
[       OK ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/1 (0 ms)
[ RUN      ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/2
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dim == 3. 
[       OK ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/2 (0 ms)
[ RUN      ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/3
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dim == 3. 
[       OK ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/3 (0 ms)
[ RUN      ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/4
[2023-1-16 15:10:26] [MLUOP] [Error]:[mluOpThreeInterpolateBackward] Check failed: grad_output_desc->dtype == weights_desc->dtype. 
[       OK ] bad_grad_output_shape_dtype_0/three_interprolate_backward_general.api_test/4 (0 ms)
[----------] 5 tests from bad_grad_output_shape_dtype_0/three_interprolate_backward_general (0 ms total)
```

**Comment by FRYao** [comment]
测试报告：测试通过

**Pull request merged**
