### PR TITLE
[TEST](prior_box): add api check cases

### PR DESCRIPTION
**Pull request by LittleReal**
## 1. Motivation

To ensure the correctness of parameters check of op.

## 2. Modification

Add api check cases for prior box

### CODE REVIEW

**Review by ling08 — APPROVED** [review]
LGTM

**Review by mahxn0 — APPROVED** [review]
LGTM ^_^

**Comment by GuangpingYuan** [comment]
LDTM

**Review by GuangpingYuan — APPROVED** [review]
LGTM

**Review by WangYuan-cn — APPROVED** [review]

**Pull request merged**
